version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest # Or a specific version like 'v2.49.1'
    container_name: prometheus
    volumes:
      - ./monitoring-stack/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # Mount the config
      - prometheus_data:/prometheus # Persist data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090" # Prometheus UI
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest # Or a specific version like '10.3.3'
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana # Persist Grafana data (dashboards, users)
    ports:
      - "3000:3000" # Grafana UI
    networks:
      - monitoring-network
    depends_on:
      - prometheus # Grafana depends on Prometheus for data

networks:
  monitoring-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: